[package]
name = "chip8"
version = "0.1.0"
authors = ["Michael Sergio <mikeserg@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.0"
structopt = "0.3.17"
c8_disasm_lib = { path = "../chip8-disassembler/c8_disasm_lib" }
cursive = "0.16"
raylib = "3.5"

